application:
  name: "OpenGarden"
  geodata.apikey: "c7cf77bade7747d9a8cb3cdd48d965bf"
server:
  port: 8080

spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0